### ISSUE TITLE
Can't be required in Node

### ISSUE THREAD

**Issue by sgwilym** [kenchris/urlpattern-polyfill#65]
Attempting to `require` this module in Node results in the following:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /node_modules/urlpattern-polyfill/dist/index.js is not supported
```

**Comment by lachlanhunt** [comment]
I also ran into this issue. I'm writing a package that, for reasons outside of my control, can't use ESM and I wanted to use this URLPattern library because it does exactly what I need. I realise it's primarily written as a polyfill for browser contexts, but being able to use this functionality in node within a CommonJS module would be extremely useful.

**Comment by kettanaito** [comment]
It looks like the package is distributed as an ES module:

https://github.com/kenchris/urlpattern-polyfill/blob/1efa9c11b6052b0c1630e7c9dd96bf8385a62ade/package.json#L14

I don't think you can circumvent this in any way. You'd have to make your package an ES module as well for such imports to work.

**Comment by sgwilym** [comment]
> I don't think you can circumvent this in any way. You'd have to make your package an ES module as well for such imports to work.

You can. Here's my fork with a properly configured package.json: https://github.com/sgwilym/urlpattern-polyfill/tree/patch-1

Other users experiencing this issue can `npm i @sgwilym/urlpattern-polyfill` while the maintainers here figure out whether they want to merge this change.

**Comment by lachlanhunt** [comment]
I was able to use `yarn patch` to patch the dependency locally with @sgwilym's changes, and it works perfectly. Please incorporate those changes into a future release.
